/*

 Copyright (c) 2017-2025, Carlos Amengual.

 Licensed under a BSD-style License. You can find the license here:
 https://css4j.github.io/LICENSE.txt

 */

// SPDX-License-Identifier: BSD-3-Clause

package io.sf.carte.uparser;

/**
 * To be implemented by listeners that handle the control-related events
 * generated by the {@link TokenProducer3}.
 */
public interface ControlHandler<E extends Exception> {

	/**
	 * At the beginning of parsing, this method is called, passing the {@link TokenControl}
	 * object that can be used to fine-control the parsing.
	 *
	 * @param control
	 *            the <code>TokenControl</code> object in charge of parsing.
	 * @throws E in case of an error when processing the tokens.
	 */
	void tokenStart(TokenControl control);

	/**
	 * A control character codepoint was found.
	 *
	 * @param index
	 *            the index at which the control codepoint was found.
	 * @param codePoint
	 *            the control codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	void control(int index, int codePoint) throws E;

	/**
	 * An unescaped FF/LF/CR control was found while assembling a quoted string.
	 *
	 * @param index
	 *            the index at which the control was found.
	 * @param codePoint
	 *            the FF/LF/CR codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	void quotedNewlineChar(int index, int codePoint) throws E;

}
