/*

 Copyright (c) 2017-2025, Carlos Amengual.

 Licensed under a BSD-style License. You can find the license here:
 https://css4j.github.io/LICENSE.txt

 */

// SPDX-License-Identifier: BSD-3-Clause

package io.sf.carte.uparser;

/**
 * To be implemented by listeners that handle the different events generated by
 * the {@link TokenProducer3}.
 */
public interface TokenHandler3<E extends Exception>
		extends ContentHandler<E>, ControlHandler<E>, TokenErrorHandler<E> {
}
