/*

 Copyright (c) 2017-2025, Carlos Amengual.

 Licensed under a BSD-style License. You can find the license here:
 https://css4j.github.io/LICENSE.txt

 */

// SPDX-License-Identifier: BSD-3-Clause

package io.sf.carte.uparser;

/**
 * Handle errors generated by the {@link TokenProducer3} and by the other token
 * handlers.
 */
public interface TokenErrorHandler<E extends Exception> {

	/**
	 * An error was found while parsing.
	 * <p>
	 * Something was found that broke the assumptions made by the parser, like an escape
	 * character at the end of the stream or an unmatched quote.
	 *
	 * @param index
	 *            the index at which the error was found.
	 * @param errCode
	 *            the error code.
	 * @param context
	 *            a context sequence. If a string was parsed, it will contain up to 16
	 *            characters before and after the error.
	 * @throws E in case that the error handler decides to throw an exception.
	 */
	void error(int index, byte errCode, CharSequence context) throws E;

}
