/*

 Copyright (c) 2017-2023, Carlos Amengual.

 Licensed under a BSD-style License. You can find the license here:
 https://css4j.github.io/LICENSE.txt

 */

// SPDX-License-Identifier: BSD-3-Clause

package io.sf.carte.uparser;

/**
 * To be implemented by listeners that handle the different events generated by
 * the {@link TokenProducer3}.
 * 
 * @param E the exception that the methods may throw.
 */
public interface TokenHandler3<E extends Exception> {

	/**
	 * At the beginning of parsing, this method is called, passing the {@link TokenControl}
	 * object that can be used to fine-control the parsing.
	 *
	 * @param control
	 *            the <code>TokenControl</code> object in charge of parsing.
	 * @throws E in case of an error when processing the tokens.
	 */
	void tokenStart(TokenControl control);

	/**
	 * A word was found by the parser (includes connector punctuation).
	 *
	 * @param index
	 *            the index at which the word was found.
	 * @param word
	 *            the word.
	 * @throws E in case of an error when processing the tokens.
	 */
	void word(int index, CharSequence word) throws E;

	/**
	 * A separator (Zs, Zl and Zp unicode categories) was found.
	 *
	 * @param index
	 *            the index at which the separator was found.
	 * @param codePoint
	 *            the codepoint of the found separator.
	 * @throws E in case of an error when processing the tokens.
	 */
	void separator(int index, int codePoint) throws E;

	/**
	 * A quoted string was found by the parser.
	 *
	 * @param index
	 *            the index at which the quoted string was found.
	 * @param quoted
	 *            the quoted sequence of characters, without the quotes.
	 * @param quote
	 *            the quote character.
	 * @throws E in case of an error when processing the tokens.
	 */
	void quoted(int index, CharSequence quoted, int quote) throws E;

	/**
	 * A quoted string was found by the parser, and contains control characters.
	 *
	 * @param index
	 *            the index at which the quoted string was found.
	 * @param quoted
	 *            the quoted sequence of characters, without the quotes.
	 * @param quoteCp
	 *            the quote character codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	void quotedWithControl(int index, CharSequence quoted, int quoteCp) throws E;

	/**
	 * An unescaped FF/LF/CR control was found while assembling a quoted string.
	 *
	 * @param index
	 *            the index at which the control was found.
	 * @param codePoint
	 *            the FF/LF/CR codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	void quotedNewlineChar(int index, int codePoint) throws E;

	/**
	 * Called when the {@code (} codepoint is found.
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @throws E in case of an error when processing the tokens.
	 */
	void leftParenthesis(int index) throws E;

	/**
	 * Called when the {@code [} codepoint is found.
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @throws E in case of an error when processing the tokens.
	 */
	void leftSquareBracket(int index) throws E;

	/**
	 * Called when the <code>{</code> codepoint is found.
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @throws E in case of an error when processing the tokens.
	 */
	void leftCurlyBracket(int index) throws E;

	/**
	 * Called when the {@code )} codepoint is found.
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @throws E in case of an error when processing the tokens.
	 */
	void rightParenthesis(int index) throws E;

	/**
	 * Called when the {@code ]} codepoint is found.
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @throws E in case of an error when processing the tokens.
	 */
	void rightSquareBracket(int index) throws E;

	/**
	 * Called when the <code>}</code> codepoint is found.
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @throws E in case of an error when processing the tokens.
	 */
	void rightCurlyBracket(int index) throws E;

	/**
	 * Called when start punctuation (Ps) codepoints are found (except characters
	 * handled by {@link #leftCurlyBracket(int)}, {@link #leftParenthesis(int)} and
	 * {@link #leftSquareBracket(int)}).
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @param codePoint
	 *            the found codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	default void startPunctuation(int index, int codePoint) throws E {
		character(index, codePoint);
	}

	/**
	 * Called when end punctuation (Pe) codepoints are found (except characters
	 * handled by {@link #rightCurlyBracket(int)}, {@link #rightParenthesis(int)}
	 * and {@link #rightSquareBracket(int)}).
	 *
	 * @param index
	 *            the index at which the codepoint was found.
	 * @param codePoint
	 *            the found codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	default void endPunctuation(int index, int codePoint) throws E {
		character(index, codePoint);
	}

	/**
	 * Other characters including punctuation (excluding connector punctuation) and symbols
	 * (Sc, Sm and Sk unicode categories) was found, that was not one of the non-alphanumeric
	 * characters allowed in words.
	 * <p>
	 * Symbols in So category are considered part of words and won't be handled by this
	 * method.
	 *
	 * @param index
	 *            the index at which the punctuation was found.
	 * @param codePoint
	 *            the codepoint of the found punctuation.
	 * @throws E in case of an error when processing the tokens.
	 */
	void character(int index, int codePoint) throws E;

	/**
	 * A codepoint preceded with a backslash was found outside of quoted text.
	 *
	 * @param index
	 *            the index at which the escaped codepoint was found.
	 * @param codePoint
	 *            the escaped codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	void escaped(int index, int codePoint) throws E;

	/**
	 * A control character codepoint was found.
	 *
	 * @param index
	 *            the index at which the control codepoint was found.
	 * @param codePoint
	 *            the control codepoint.
	 * @throws E in case of an error when processing the tokens.
	 */
	void control(int index, int codePoint) throws E;

	/**
	 * A commented string was found by the parser.
	 *
	 * @param index
	 *            the index at which the commented string was found.
	 * @param commentType
	 *            the type of comment.
	 * @param comment
	 *            the commented string.
	 * @throws E in case of an error when processing the tokens.
	 */
	void commented(int index, int commentType, String comment) throws E;

	/**
	 * The stream that was being parsed reached its end.
	 *
	 * @param len
	 *            the length of the processed stream.
	 * @throws E in case of an error when processing the tokens.
	 */
	void endOfStream(int len) throws E;

	/**
	 * An error was found while parsing.
	 * <p>
	 * Something was found that broke the assumptions made by the parser, like an escape
	 * character at the end of the stream or an unmatched quote.
	 *
	 * @param index
	 *            the index at which the error was found.
	 * @param errCode
	 *            the error code.
	 * @param context
	 *            a context sequence. If a string was parsed, it will contain up to 16
	 *            characters before and after the error.
	 * @throws E in case that the error handler decides to throw an exception.
	 */
	void error(int index, byte errCode, CharSequence context) throws E;
}
